projectType: extension
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: -DminVersion=4.4.0 -DruntimeProduct=MULE_EE
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -DminVersion=4.6.0 -DruntimeProduct=MULE_EE
